networks:
  retrofun:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      # POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - retrofun
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  test_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    networks:
      - retrofun
    ports:
      - "5433:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # DB_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - retrofun
    env_file:
      - .env
volumes:
  db-data:
  test-db-data:
