- name: Create filesystem for Postgres data
  filesystem:
    fstype: xfs
    dev: /dev/xvdf

- name: Create mount directory
  file:
    path: /var/lib/postgresql/data
    state: directory
    owner: postgres
    group: postgres
    mode: 0700

- name: Mount data volume
  mount:
    path: /var/lib/postgresql/data
    src: /dev/xvdf
    fstype: xfs
    opts: noatime
    state: mounted
